POST http://localhost:3007/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "mansouryathi@gmail.com",
  "password": "passer133"
}

###

POST http://localhost:3007/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "mansouryathi@gmail.com",
  "password": "passer133"

}